feat: UNIC-1349 refactor OptimizeDeltaTables
Ferlab-Ste-Justine/datalake-lib pull request #237
Opened 2024-09-05 20:01 UTC by zoemcl

2024-09-05 20:12 UTC, laurabegin requested changes

2024-09-05 20:12 UTC, laurabegin commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/utils/OptimizeDeltaTables.scala
> +    datasetConfs.foreach { ds =>
Pourquoi tu as besoin de faire ça?

2024-09-05 20:17 UTC, zoemcl commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/utils/OptimizeDeltaTables.scala
> +    datasetConfs.foreach { ds =>
si quelqu'un passe un dataset_id invalid dans la liste, la job va fail avant de commencer l'optimization. Avant si il y a un ID invalid, la job pourrait finir avec la moitié de l'optimization faite

2024-09-05 20:19 UTC, laurabegin commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/utils/OptimizeDeltaTables.scala
> +    datasetConfs.foreach { ds =>
Le fold va fail car conf.getDataset va planter

2024-09-05 20:19 UTC, laurabegin commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/utils/OptimizeDeltaTables.scala
> +    datasetConfs.foreach { ds =>
Tu pourrais plutôt envelopper l'intérieur du foreach dans un try

2024-09-05 20:20 UTC, laurabegin commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/utils/OptimizeDeltaTables.scala
> +    datasetConfs.foreach { ds =>
Pis loguer l'erreur

2024-09-06 18:10 UTC, laurabegin approved these changes

2024-09-09 15:42 UTC, merged