feat: CLIN-2536 normalize gnomad 4
Ferlab-Ste-Justine/datalake-lib pull request #245
Opened 2024-12-02 14:17 UTC by meek0

2024-12-02 16:43 UTC, laurabegin requested changes

2024-12-02 16:43 UTC, laurabegin commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/publictables/PublicDatasets.scala
> +          DatasetConf("raw_gnomad_genomes_v4"        , alias, "/release/4.1/vcf/genomes/gnomad.genomes.v4.1.sites.chr[^M]*.vcf.bgz", VCF  , OverWrite , readoptions = Map("flattenInfoFields" -> "true"
Oh je vois qu'on a setup un gnomad storage ce qui permet de directement downloader depuis le s3 de gnomad?

2024-12-02 16:43 UTC, laurabegin commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/publictables/normalized/gnomad/GnomadV4.scala
> +  }
Duplicated code

2024-12-03 13:00 UTC, meek0 commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/publictables/PublicDatasets.scala
> +          DatasetConf("raw_gnomad_genomes_v4"        , alias, "/release/4.1/vcf/genomes/gnomad.genomes.v4.1.sites.chr[^M]*.vcf.bgz", VCF  , OverWrite , readoptions = Map("flattenInfoFields" -> "true"
En effet, je vois un config avec le bucket de gnomad (through le storageId), ce qui voudrait dire que tout ce qu'il faut pour l'etl c'est de trigger le script?

2024-12-03 13:12 UTC, meek0 commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/publictables/normalized/gnomad/GnomadV4.scala
> +  }
Je vois que le flattenInfo de GenomicImplicits fonctionne bien, je bascule sur ça.

2024-12-03 14:28 UTC, laurabegin commented on datalake-spark3/src/main/scala/bio/ferlab/datalake/spark3/publictables/PublicDatasets.scala
> +          DatasetConf("raw_gnomad_genomes_v4"        , alias, "/release/4.1/vcf/genomes/gnomad.genomes.v4.1.sites.chr[^M]*.vcf.bgz", VCF  , OverWrite , readoptions = Map("flattenInfoFields" -> "true"
On dirait. Faudrait tester.

2024-12-03 14:28 UTC, laurabegin approved these changes

2024-12-03 14:55 UTC, merged